name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      VIEWER_EMAIL: ${{ secrets.VIEWER_EMAIL }}
      VIEWER_PASSWORD: ${{ secrets.VIEWER_PASSWORD }}
      DB_HOST: 127.0.0.1
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: qa_admin_portal

    steps:
      - name: Checkout automation repository
        uses: actions/checkout@v4

      - name: Checkout application under test
        uses: actions/checkout@v4
        with:
          repository: binfengke/qa-admin-portal-automation
          path: qa-admin-portal-automation

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Prepare application for CI
        shell: bash
        run: |
          echo "Checking application healthcheck..."

          grep -q 'wget -q -O - http://localhost:8080/' \
            qa-admin-portal-automation/docker-compose.yml

          echo "Updating web healthcheck for CI..."

          sed -i \
            's|wget -q -O - http://localhost:8080/|wget -q -O - http://127.0.0.1:8080/|' \
            qa-admin-portal-automation/docker-compose.yml

          echo "Updated healthcheck:"
          grep -A6 -B2 'healthcheck:' \
            qa-admin-portal-automation/docker-compose.yml

      - name: Start app stack
        run: docker compose -f qa-admin-portal-automation/docker-compose.yml up -d --build --wait

      - name: Run Playwright tests
        run: npx playwright test

      - name: Stop app stack
        if: always()
        run: docker compose -f qa-admin-portal-automation/docker-compose.yml down -v

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
